spring.application.name=payment-service
server.port=8084
spring.mongodb.uri=${SPRING_MONGODB_URI}

liquibase.change-log=db/changelog/db.changelog-master.yaml

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI}

app.kafka.topic=${APP_KAFKA_TOPIC}
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.acks=-1
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

random.num.url=${RANDOM_NUM_URL}