spring.application.name=payment-service
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=payment_db
spring.mongodb.username=admin
spring.mongodb.password=admin
spring.mongodb.authentication-database=admin
#spring.mongodb.uri=mongodb://admin:admin@mongodb:27017/payment_db?authSource=admin
